// <auto-generated />
namespace Attempt2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Adding_Summary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding_Summary));
        
        string IMigrationMetadata.Id
        {
            get { return "201906081436120_Adding_Summary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
